# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Defaults
defaults:

  # Dataset
  - dataset/mock

  # Model
  # - model/stormcast

  # Training
  - training/default

  # Sampler
  - sampler/edm_deterministic

  # Hydra
  - hydra/default

  - _self_

training:
  num_data_workers: 2
  validation_plot_variables: ["state_0"]
  log_to_wandb: True
  wandb_mode: "offline"  # not using online logging while testing
  log_to_tensorboard: True

  print_progress_freq: 5 # How often to print progress, measured in number of training steps
  checkpoint_freq: 5 # How often to save the checkpoints, measured in number of training steps
  validation_freq: 5 # how often to record the validation loss, measured in number of training steps
  batch_size: 1
  total_train_steps: 10

  scheduler:
    name: null

  loss:
    type: 'regression'

model:
  architecture: unet
  hyperparameters:
    model_channels: 32
    channel_mult: [1, 2]
    num_blocks: 2

  regression_conditions: ["state", "background", "invariant"]
  diffusion_conditions: ["state", "background", "invariant"]

dataset:
  num_scalar_cond_channels: 0